question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "Au on the Periodic Table refers to which element?",
     "correct_answer": "Gold", "incorrect_answers": ["Silver", "Oxygen", "Nickel"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "The Xenomorph from the science fiction film &quot;Alien&quot; has acidic blood.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Which of the following is not a prosecutor in the &quot;Ace Attorney&quot; video game series?",
     "correct_answer": "Jake Marshall",
     "incorrect_answers": ["Godot", "Miles Edgeworth", "Jacques Portsman"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Brian May was the guitarist for which band?",
     "correct_answer": "Queen",
     "incorrect_answers": ["Pink Floyd", "Rolling Stones", "The Doors"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "What vault in the video game &quot;Fallout 3&quot; is the home of multiple clones named Gary?",
     "correct_answer": "Vault 108",
     "incorrect_answers": ["Vault 101", "Vault 87", "Vault 21"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "What is the maximum HP in Terraria?", "correct_answer": "500",
     "incorrect_answers": ["400", "1000", "100"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "All of the following programs are classified as raster graphics editors EXCEPT:",
     "correct_answer": "Inkscape",
     "incorrect_answers": ["Paint.NET", "GIMP", "Adobe Photoshop"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "In &quot;Hexadecimal&quot;, what color would be displayed from the color code? &quot;#00FF00&quot;?",
     "correct_answer": "Green", "incorrect_answers": ["Red", "Blue", "Yellow"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Television",
     "question": "Which of these Nickelodeon game shows aired first?",
     "correct_answer": "Double Dare",
     "incorrect_answers": ["Nick Arcade", "Finders Keepers", "Nickelodeon Guts"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The fourth funnel of the RMS Titanic was fake "
                 "designed to make the ship look more powerful and symmetrical.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
